apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.apps.registryPublic.claims.data }}
  namespace: {{ .Values.apps.registryPublic.namespace }}
  labels:
    app: {{ .Values.apps.registryPublic.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apps.registryPublic.storage }}
