{{- $configHash := include (print $.Template.BasePath "/registry-configmap.yaml") $ | sha256sum }}
{{ include "platform.deployment" (dict "app" .Values.apps.registryPublic "checksums" (dict "config" $configHash)) }}
