{{ include "platform.service" (dict "app" .Values.apps.registryPublic) }}
---
{{ include "platform.service" (dict "app" .Values.apps.registryPublicUi) }}
---
{{ include "platform.service" (dict "app" .Values.apps.registryPublicUiApi) }}
