{{- $configHash := include (print $.Template.BasePath "/ui-api-configmap.yaml") $ | sha256sum }}
{{ include "platform.deployment" (dict "app" .Values.apps.registryPublicUiApi "checksums" (dict "config" $configHash)) }}
