{{- $secretHash := include (print $.Template.BasePath "/ui-secret.yaml") $ | sha256sum }}
{{ include "platform.deployment" (dict "app" .Values.apps.registryPublicUi "checksums" (dict "secret" $secretHash)) }}
