apiVersion: v1
kind: Secret
metadata:
  name: headlamp-admin-token
  namespace: {{ .Values.apps.headlamp.namespace }}
  annotations:
    kubernetes.io/service-account.name: headlamp
type: kubernetes.io/service-account-token
