apiVersion: v2
name: litellm
version: 0.1.0
type: application
dependencies:
  - name: postgres
    version: ">=0.1.0"
    repository: file://../../shared/postgres
  - name: platform
    version: ">=0.4.0"
    repository: file://../../shared/platform
