apps:
  litellm:
    images:
      litellm:
        image: ghcr.io/berriai/litellm
        imageTag: v1.83.7-stable
      postgres:
        image: postgres
        imageTag: "17.9"

    replicas: 1

    configMaps:
      config: litellm-config

    claims:
      data: litellm-data
      postgresData: litellm-postgres-data

    postgres:
      serviceName: litellm-postgres
      port: 5432
      dbName: litellm
      dbUser: postgres
      dbPassword: __LITELLM_POSTGRES_PASSWORD__
      storage: 5Gi

    storage:
      data: 1Gi
