apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.apps.portainer.claims.data }}
  namespace: {{ .Values.apps.portainer.namespace }}
  labels:
    app: {{ .Values.apps.portainer.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apps.portainer.storage.data }}
