apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.apps.portainer.appName }}
  labels:
    app: {{ .Values.apps.portainer.appName }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.apps.portainer.appName }}
  labels:
    app: {{ .Values.apps.portainer.appName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.apps.portainer.appName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.apps.portainer.appName }}
    namespace: {{ .Values.apps.portainer.namespace }}
