apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.honcho.appName }}
  namespace: {{ .Values.apps.honcho.namespace }}
  labels:
    app: {{ .Values.apps.honcho.appName }}
spec:
  ports:
    - name: http
      port: {{ .Values.apps.honcho.port }}
      targetPort: {{ .Values.apps.honcho.port }}
  selector:
    app: {{ .Values.apps.honcho.appName }}
