apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apps.caddy.private.configMaps.caddyfile }}
  namespace: {{ .Values.apps.caddy.namespace }}
  labels:
    app: {{ .Values.apps.caddy.appName }}
data:
  Caddyfile: |
    {
    	email guneetaggarwal@gmail.com
    	acme_dns cloudflare {env.CLOUDFLARE_API_TOKEN}
    	layer4 {
    		:{{ .Values.apps.devDb.postgresPort }} {
    			route {
    				proxy {
    					upstream dev-db-postgres.{{ .Values.apps.devDb.namespace }}.svc.cluster.local:{{ .Values.apps.devDb.postgresPort }}
    				}
    			}
    		}
    	}
    }
    
    :80 {
    	respond /healthz 200
    }
    
    headlamp.guneet.xyz {
    	reverse_proxy {{ .Values.apps.headlamp.appName }}.{{ .Values.apps.headlamp.namespace }}.svc.cluster.local:{{ .Values.apps.headlamp.port }}
    }
    
    llm.guneet.xyz {
    	reverse_proxy {{ .Values.apps.litellm.appName }}.{{ .Values.apps.litellm.namespace }}.svc.cluster.local:{{ .Values.apps.litellm.port }}
    }

    chat.guneet.xyz {
    	reverse_proxy {{ .Values.apps.openwebui.appName }}.{{ .Values.apps.openwebui.namespace }}.svc.cluster.local:{{ .Values.apps.openwebui.port }}
    }

    cr.guneet.xyz {
    	reverse_proxy /v2/* {{ .Values.apps.registry.appName }}.{{ .Values.apps.registry.namespace }}.svc.cluster.local:{{ .Values.apps.registry.port }}
    	reverse_proxy {{ .Values.apps.registryUi.appName }}.{{ .Values.apps.registryUi.namespace }}.svc.cluster.local:{{ .Values.apps.registryUi.port }}
    }

    portainer.guneet.xyz {
    	reverse_proxy {{ .Values.apps.portainer.appName }}.{{ .Values.apps.portainer.namespace }}.svc.cluster.local:{{ .Values.apps.portainer.port }}
    }

    home.guneet.xyz {
    	reverse_proxy {{ .Values.apps.homepage.appName }}.{{ .Values.apps.homepage.namespace }}.svc.cluster.local:{{ .Values.apps.homepage.port }}
    }

    db.guneet.xyz {
    	reverse_proxy {{ .Values.apps.devDb.appName }}.{{ .Values.apps.devDb.namespace }}.svc.cluster.local:{{ .Values.apps.devDb.port }}
    }

    honcho.guneet.xyz {
    	@root path /
    	redir @root /docs 307
    	reverse_proxy {{ .Values.apps.honcho.appName }}.{{ .Values.apps.honcho.namespace }}.svc.cluster.local:{{ .Values.apps.honcho.port }}
    }

    notes.guneet.xyz {
    	reverse_proxy {{ .Values.apps.zennotes.appName }}.{{ .Values.apps.zennotes.namespace }}.svc.cluster.local:{{ .Values.apps.zennotes.port }}
    }

    hermes.guneet.xyz {
        reverse_proxy http://100.101.181.45:9119
    }

    chat.hermes.guneet.xyz {
        reverse_proxy http://100.101.181.45:8787
    }

    plane.guneet.xyz {
    	@api path /api/* /auth/*
    	reverse_proxy @api {{ .Values.apps.plane.services.api.name }}.{{ .Values.apps.plane.namespace }}.svc.cluster.local:{{ .Values.apps.plane.services.api.port }}

    	@spaces path /spaces /spaces/*
    	reverse_proxy @spaces {{ .Values.apps.plane.services.space.name }}.{{ .Values.apps.plane.namespace }}.svc.cluster.local:{{ .Values.apps.plane.services.space.port }}

    	@godmode path /god-mode /god-mode/*
    	reverse_proxy @godmode {{ .Values.apps.plane.services.admin.name }}.{{ .Values.apps.plane.namespace }}.svc.cluster.local:{{ .Values.apps.plane.services.admin.port }}

    	@live path /live /live/*
    	reverse_proxy @live {{ .Values.apps.plane.services.live.name }}.{{ .Values.apps.plane.namespace }}.svc.cluster.local:{{ .Values.apps.plane.services.live.port }} {
    		flush_interval -1
    	}

    	@uploads path /uploads /uploads/*
    	reverse_proxy @uploads {{ .Values.apps.plane.services.minio.name }}.{{ .Values.apps.plane.namespace }}.svc.cluster.local:{{ .Values.apps.plane.services.minio.port }}

    	reverse_proxy {{ .Values.apps.plane.services.web.name }}.{{ .Values.apps.plane.namespace }}.svc.cluster.local:{{ .Values.apps.plane.services.web.port }}

    	request_body {
    		max_size 100MB
    	}
    }
