apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apps.caddy.public.configMaps.caddyfile }}
  namespace: {{ .Values.apps.caddy.namespace }}
  labels:
    app: {{ .Values.apps.caddy.appName }}
data:
  Caddyfile: |
    {
    	email guneetaggarwal@gmail.com
    	acme_dns cloudflare {env.CLOUDFLARE_API_TOKEN}
    }
    
    :80 {
    	respond /healthz 200
    }
    
    walls.guneet.dev {
    	reverse_proxy {{ .Values.apps.walls.appName }}.{{ .Values.apps.walls.namespace }}.svc.cluster.local:{{ .Values.apps.walls.port }}
    }
    
    llm.guneet.dev {
    	reverse_proxy {{ .Values.apps.litellm.appName }}.{{ .Values.apps.litellm.namespace }}.svc.cluster.local:{{ .Values.apps.litellm.port }}
    }
    
    infisical.guneet.dev {
    	reverse_proxy {{ .Values.apps.infisical.appName }}.{{ .Values.apps.infisical.namespace }}.svc.cluster.local:{{ .Values.apps.infisical.port }}
    }
    
    demo.guneet.dev {
    	handle_errors 502 {
    		reverse_proxy {{ .Values.apps.demoFallback.appName }}.{{ .Values.apps.demoFallback.namespace }}.svc.cluster.local:{{ .Values.apps.demoFallback.port }}
    	}
    	reverse_proxy {{ .Values.apps.demo.appName }}.{{ .Values.apps.demo.namespace }}.svc.cluster.local:{{ .Values.apps.demo.port }}
    }

    cr.guneet.dev {
    	reverse_proxy /auth* {{ .Values.apps.registryPublic.authAppName }}.{{ .Values.apps.registryPublic.namespace }}.svc.cluster.local:{{ .Values.apps.registryPublic.authPort }}

    	reverse_proxy /v2/* {{ .Values.apps.registryPublic.appName }}.{{ .Values.apps.registryPublic.namespace }}.svc.cluster.local:{{ .Values.apps.registryPublic.port }} {
    		flush_interval -1
    		transport http {
    			read_timeout 10m
    			write_timeout 10m
    		}
    	}

    	request_body {
    		max_size 0
    	}
    }

    books.guneet.dev {
    	reverse_proxy https://books.guneet.xyz {
    		header_up Host {upstream_hostport}
    	}
    }

    abs.guneet.dev {
    	reverse_proxy https://abs.guneet.xyz {
    		header_up Host {upstream_hostport}
    	}
    }

    matrix.guneet.dev {
    	handle /.well-known/matrix/server {
    		header Content-Type application/json
    		header Access-Control-Allow-Origin *
    		respond `{"m.server": "matrix.guneet.dev:443"}` 200
    	}
    	handle /.well-known/matrix/client {
    		header Content-Type application/json
    		header Access-Control-Allow-Origin *
    		respond `{"m.homeserver": {"base_url": "https://matrix.guneet.dev"}}` 200
    	}
    	handle {
    		request_body {
    			max_size 100MB
    		}
    		reverse_proxy {{ .Values.apps.synapse.appName }}.{{ .Values.apps.synapse.namespace }}.svc.cluster.local:{{ .Values.apps.synapse.port }}
    	}
    }

    chat.guneet.dev {
    	reverse_proxy {{ .Values.apps.element.appName }}.{{ .Values.apps.element.namespace }}.svc.cluster.local:{{ .Values.apps.element.port }}
    }


