apiVersion: v1
kind: Secret
metadata:
  name: registry-public-basic-auth
  namespace: {{ .Values.apps.caddy.namespace }}
  labels:
    app: {{ .Values.apps.caddy.appName }}
type: Opaque
stringData:
  REGISTRY_PUBLIC_USERNAME: __REGISTRY_PUBLIC_USERNAME__
  REGISTRY_PUBLIC_HTPASSWD: __REGISTRY_PUBLIC_HTPASSWD__
