{{- $secretHash := include (print $.Template.BasePath "/pgui-secret.yaml") $ | sha256sum }}
{{ include "platform.deployment" (dict "app" .Values.apps.devDb "checksums" (dict "secret" $secretHash)) }}
