apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.apps.litellm.namespace }}
  labels:
    app: {{ .Values.apps.litellm.appName }}
type: Opaque
stringData:
  GITHUB_API_KEY: __GITHUB_API_KEY__
  LITELLM_MASTER_KEY: __LITELLM_MASTER_KEY__
  SMTP_HOST: {{ .Values.smtp.host }}
  SMTP_USERNAME: __SMTP_USERNAME__
  SMTP_PASSWORD: __SMTP_PASSWORD__
  SMTP_SENDER_ADDRESS: {{ .Values.smtp.mailFrom }}
  DATABASE_URL: postgresql://{{ .Values.apps.litellm.postgres.dbUser }}:{{ .Values.apps.litellm.postgres.dbPassword }}@{{ .Values.apps.litellm.postgres.serviceName }}:{{ .Values.apps.litellm.postgres.port }}/{{ .Values.apps.litellm.postgres.dbName }}
