{{- $configHash := include (print $.Template.BasePath "/litellm-configmap.yaml") $ | sha256sum }}
{{- $secretHash := include (print $.Template.BasePath "/litellm-secret.yaml") $ | sha256sum }}
{{ include "platform.deployment" (dict "app" .Values.apps.litellm "checksums" (dict "config" $configHash "secret" $secretHash)) }}
