apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.apps.litellm.claims.data }}
  namespace: {{ .Values.apps.litellm.namespace }}
  labels:
    app: {{ .Values.apps.litellm.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apps.litellm.dataStorage }}
