apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.litellm.postgres.serviceName }}
  namespace: {{ .Values.apps.litellm.namespace }}
  labels:
    app: {{ .Values.apps.litellm.postgres.serviceName }}
spec:
  ports:
    - name: postgres
      port: {{ .Values.apps.litellm.postgres.port }}
      targetPort: {{ .Values.apps.litellm.postgres.port }}
  selector:
    app: {{ .Values.apps.litellm.postgres.serviceName }}
