apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.apps.litellm.namespace }}
  labels:
    app: {{ .Values.apps.litellm.postgres.serviceName }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.apps.litellm.postgres.dbPassword }}
