apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.openwebui.appName }}
  namespace: {{ .Values.apps.openwebui.namespace }}
  labels:
    app: {{ .Values.apps.openwebui.appName }}
spec:
  replicas: {{ .Values.apps.openwebui.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apps.openwebui.appName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.apps.openwebui.appName }}
    spec:
      nodeSelector:
        role: primary
      containers:
        - name: openwebui
          image: {{ .Values.apps.openwebui.images.openwebui.image }}:{{ .Values.apps.openwebui.images.openwebui.imageTag }}
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 2Gi
          ports:
            - containerPort: {{ .Values.apps.openwebui.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.apps.openwebui.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.apps.openwebui.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
          volumeMounts:
            - mountPath: /app/backend/data
              name: {{ .Values.apps.openwebui.claims.data }}
      volumes:
        - name: {{ .Values.apps.openwebui.claims.data }}
          persistentVolumeClaim:
            claimName: {{ .Values.apps.openwebui.claims.data }}
