apiVersion: v1
kind: Secret
metadata:
  name: pgui-secret
  namespace: {{ .Values.apps.devDb.namespace }}
  labels:
    app: {{ .Values.apps.devDb.appName }}
type: Opaque
stringData:
  DB_1_PASSWORD: {{ .Values.apps.devDb.postgres.dbPassword }}
