services:
  caddy:
    build:
      context: .
    container_name: caddy-private
    restart: unless-stopped
    ports:
      - 100.100.2.1:80:80 # int
      - 100.100.2.1:443:443 # int
      - 100.100.2.1:443:443/udp # int
    networks:
      - caddy-private
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
networks:
  caddy-private:
    external: true
