{{- $configHash := include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
{{ include "platform.deployment" (dict "app" .Values.apps.homepage "checksums" (dict "config" $configHash)) }}
