apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.apps.homepage.appName }}
  labels:
    app: {{ .Values.apps.homepage.appName }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.apps.homepage.appName }}
  labels:
    app: {{ .Values.apps.homepage.appName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.apps.homepage.appName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.apps.homepage.appName }}
    namespace: {{ .Values.apps.homepage.namespace }}
