apps:
  walls:
    images:
      walls:
        image: kvqn/walls
        imageTag: "1.7.0"
      migrate:
        image: kvqn/walls-migrate
        imageTag: "1.7.0"
      postgres:
        image: postgres
        imageTag: "17.9-alpine"

    replicas: 1

    domain: walls.guneet.dev

    postgres:
      serviceName: walls-postgres
      port: 5432
      dbName: walls
      dbUser: walls
      dbPassword: __WALLS_POSTGRES_PASSWORD__
      storage: 5Gi

    claims:
      postgresData: walls-postgres-data

smtp:
  mailFrom: noreply@guneet.dev
