apps:
  walls:
    image: kvqn/walls
    imageTag: "1.7.0"

    images:
      migrate:
        image: kvqn/walls-migrate
        imageTag: "1.7.0"
      postgres:
        image: postgres
        imageTag: "17.9-alpine"

    replicas: 1

    securityContext:
      allowPrivilegeEscalation: false

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi

    envFrom:
      - secretRef:
          name: app-secret

    initContainers:
      - name: db-migrate
        image: kvqn/walls-migrate:1.7.0
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DATABASE_URL

    probes:
      readiness:
        path: /
        initialDelaySeconds: 5
        periodSeconds: 5
      liveness:
        path: /
        initialDelaySeconds: 15
        periodSeconds: 10

    domain: walls.guneet.dev

    postgres:
      serviceName: walls-postgres
      port: 5432
      dbName: walls
      dbUser: walls
      dbPassword: __WALLS_POSTGRES_PASSWORD__
      storage: 5Gi

    claims:
      postgresData: walls-postgres-data
