apps:
  coturn:
    appName: coturn
    namespace: coturn
    image:
      repository: coturn/coturn
      tag: "4.6.2-r11"
    replicas: 1
    realm: matrix.guneet.dev
    externalIp: "20.219.12.93"
    relayPortMin: 49160
    relayPortMax: 49200
    tlsDomain: turn.matrix.guneet.dev
    caddyPvcName: caddy-data
    caddyCertsHostPath: "/var/lib/rancher/k3s/storage/pvc-e8515c4e-a34d-4722-ae35-1eb83d612842_caddy_caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/turn.matrix.guneet.dev"
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
