apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.apps.walls.namespace }}
  labels:
    app: {{ .Values.apps.walls.postgres.serviceName }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.apps.walls.postgres.dbUser }}
  POSTGRES_PASSWORD: {{ .Values.apps.walls.postgres.dbPassword }}
  POSTGRES_DB: {{ .Values.apps.walls.postgres.dbName }}
