apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.walls.appName }}
  namespace: {{ .Values.apps.walls.namespace }}
  labels:
    app: {{ .Values.apps.walls.appName }}
spec:
  replicas: {{ .Values.apps.walls.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apps.walls.appName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.apps.walls.appName }}
    spec:
      nodeSelector:
        role: primary
      initContainers:
        - name: db-migrate
          image: {{ .Values.apps.walls.images.migrate.image }}:{{ .Values.apps.walls.images.migrate.imageTag }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_URL
      containers:
        - name: walls
          image: {{ .Values.apps.walls.images.walls.image }}:{{ .Values.apps.walls.images.walls.imageTag }}
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 256Mi
          ports:
            - containerPort: {{ .Values.apps.walls.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: app-secret
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.apps.walls.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.apps.walls.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
