apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.walls.appName }}
  namespace: {{ .Values.apps.walls.namespace }}
  labels:
    app: {{ .Values.apps.walls.appName }}
spec:
  ports:
    - name: http
      port: {{ .Values.apps.walls.port }}
      targetPort: {{ .Values.apps.walls.port }}
  selector:
    app: {{ .Values.apps.walls.appName }}
