apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.apps.walls.namespace }}
  labels:
    app: {{ .Values.apps.walls.appName }}
type: Opaque
stringData:
  APP_URL: "https://{{ .Values.apps.walls.domain }}"
  AUTH_SECRET: __WALLS_AUTH_SECRET__
  SMTP_HOST: {{ .Values.smtp.host }}
  SMTP_PORT: "{{ .Values.smtp.port }}"
  SMTP_USERNAME: __SMTP_USERNAME__
  SMTP_PASSWORD: __SMTP_PASSWORD__
  SMTP_MAIL_FROM: {{ .Values.smtp.mailFrom }}
  DATABASE_URL: postgresql://{{ .Values.apps.walls.postgres.dbUser }}:{{ .Values.apps.walls.postgres.dbPassword }}@{{ .Values.apps.walls.postgres.serviceName }}:{{ .Values.apps.walls.postgres.port }}/{{ .Values.apps.walls.postgres.dbName }}
