{{- $secretHash := include (print $.Template.BasePath "/walls-secret.yaml") $ | sha256sum }}
{{ include "platform.deployment" (dict "app" .Values.apps.walls "checksums" (dict "secret" $secretHash)) }}
