name: syncthing
services:
  tailscale:
    image: tailscale/tailscale
    pull_policy: always
    container_name: syncthing-ts
    hostname: syncthing-cloud
    restart: always
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_EXTRA_ARGS: --advertise-tags=tag:container
    volumes:
      - ./tailscale:/var/lib/tailscale
    networks:
      - caddy-private
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    pull_policy: always
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./syncthing:/config
      - ./data:/data
    restart: always
    network_mode: service:tailscale
networks:
  caddy-private:
    external: true
