apiVersion: v2
name: dev-db
version: 0.1.0
type: application
dependencies:
  - name: postgres
    version: ">=0.1.0"
    repository: file://../../shared/postgres
  - name: platform
    version: ">=0.2.0"
    repository: file://../../shared/platform
