apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.registry.appName }}
  namespace: {{ .Values.apps.registry.namespace }}
  labels:
    app: {{ .Values.apps.registry.appName }}
spec:
  ports:
    - name: http
      port: {{ .Values.apps.registry.port }}
      targetPort: {{ .Values.apps.registry.port }}
  selector:
    app: {{ .Values.apps.registry.appName }}
