apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apps.registry.configMaps.registryConfig }}
  namespace: {{ .Values.apps.registry.namespace }}
  labels:
    app: {{ .Values.apps.registry.appName }}
data:
  REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "[https://{{ .Values.apps.registry.domain }}]"
  REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: "[HEAD,GET,OPTIONS,DELETE]"
  REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: "[true]"
  REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: "[Authorization,Accept,Cache-Control]"
  REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: "[Docker-Content-Digest]"
