apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.apps.registry.claims.registryData }}
  namespace: {{ .Values.apps.registry.namespace }}
  labels:
    app: {{ .Values.apps.registry.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apps.registry.storage }}
