apiVersion: v1
kind: Secret
metadata:
  name: ui-secret
  namespace: {{ .Values.apps.registry.namespace }}
  labels:
    app: {{ .Values.apps.registryUi.appName }}
type: Opaque
stringData:
  REGISTRY_USERNAME: __REGISTRY_USERNAME__
  REGISTRY_PASSWORD: __REGISTRY_PASSWORD__
  SESSION_SECRET: __REGISTRY_SESSION_SECRET__
