apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.registryPublic.authAppName }}
  namespace: {{ .Values.apps.registryPublic.namespace }}
  labels:
    app: {{ .Values.apps.registryPublic.authAppName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.apps.registryPublic.authAppName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: {{ .Values.apps.registryPublic.authAppName }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/auth-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/auth-signing-secret.yaml") . | sha256sum }}
        checksum/htpasswd-secret: {{ include (print $.Template.BasePath "/htpasswd-secret.yaml") . | sha256sum }}
        checksum/admin-hash: "__REGISTRY_PUBLIC_ADMIN_HASH__"
        checksum/ci-hash: "__REGISTRY_PUBLIC_CI_HASH__"
    spec:
      nodeSelector:
        role: primary
      containers:
        - name: auth
          image: {{ .Values.apps.registryPublic.images.auth.image }}:{{ .Values.apps.registryPublic.images.auth.imageTag }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 128Mi
          ports:
            - containerPort: {{ .Values.apps.registryPublic.authPort }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.apps.registryPublic.authPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.apps.registryPublic.authPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - mountPath: /config
              name: auth-config
              readOnly: true
            - mountPath: /htpasswd
              name: htpasswd
              readOnly: true
            - mountPath: /certs
              name: auth-signing
              readOnly: true
      volumes:
        - name: auth-config
          configMap:
            name: {{ .Values.apps.registryPublic.configMaps.authConfig }}
            items:
              - key: auth_config.yml
                path: auth_config.yml
        - name: htpasswd
          secret:
            secretName: {{ .Values.apps.registryPublic.secrets.htpasswd }}
        - name: auth-signing
          secret:
            secretName: {{ .Values.apps.registryPublic.secrets.authSigning }}
