apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apps.registryPublic.secrets.authSigning }}
  namespace: {{ .Values.apps.registryPublic.namespace }}
  labels:
    app: {{ .Values.apps.registryPublic.appName }}
type: Opaque
data:
  tls.key: __REGISTRY_PUBLIC_AUTH_TLS_KEY__
  tls.crt: __REGISTRY_PUBLIC_AUTH_TLS_CRT__
