apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apps.registryPublic.secrets.htpasswd }}
  namespace: {{ .Values.apps.registryPublic.namespace }}
  labels:
    app: {{ .Values.apps.registryPublic.authAppName }}
type: Opaque
data:
  htpasswd: __REGISTRY_PUBLIC_HTPASSWD_B64__
