apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.registryPublic.appName }}
  namespace: {{ .Values.apps.registryPublic.namespace }}
  labels:
    app: {{ .Values.apps.registryPublic.appName }}
spec:
  replicas: {{ .Values.apps.registryPublic.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apps.registryPublic.appName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: {{ .Values.apps.registryPublic.appName }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/registry-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/auth-signing-secret.yaml") . | sha256sum }}
    spec:
      nodeSelector:
        role: primary
      containers:
        - name: registry
          image: {{ .Values.apps.registryPublic.images.registry.image }}:{{ .Values.apps.registryPublic.images.registry.imageTag }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          ports:
            - containerPort: {{ .Values.apps.registryPublic.port }}
              protocol: TCP
          env:
            - name: OTEL_TRACES_EXPORTER
              value: none
          readinessProbe:
            tcpSocket:
              port: {{ .Values.apps.registryPublic.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.apps.registryPublic.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: /var/lib/registry
              name: registry-data
            - mountPath: /etc/distribution/config.yml
              name: registry-config
              subPath: config.yml
              readOnly: true
            - mountPath: /config
              name: registry-config
              readOnly: true
            - mountPath: /certs
              name: auth-signing
              readOnly: true
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: {{ .Values.apps.registryPublic.claims.data }}
        - name: registry-config
          configMap:
            name: {{ .Values.apps.registryPublic.configMaps.registryConfig }}
        - name: auth-signing
          secret:
            secretName: {{ .Values.apps.registryPublic.secrets.authSigning }}
