apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apps.registryPublic.configMaps.registryConfig }}
  namespace: {{ .Values.apps.registryPublic.namespace }}
  labels:
    app: {{ .Values.apps.registryPublic.appName }}
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :{{ .Values.apps.registryPublic.port }}
      headers:
        X-Content-Type-Options: [nosniff]
