apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.registryPublic.appName }}
  namespace: {{ .Values.apps.registryPublic.namespace }}
  labels:
    app: {{ .Values.apps.registryPublic.appName }}
spec:
  ports:
    - name: http
      port: {{ .Values.apps.registryPublic.port }}
      targetPort: {{ .Values.apps.registryPublic.port }}
  selector:
    app: {{ .Values.apps.registryPublic.appName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.registryPublic.authAppName }}
  namespace: {{ .Values.apps.registryPublic.namespace }}
  labels:
    app: {{ .Values.apps.registryPublic.authAppName }}
spec:
  ports:
    - name: http
      port: {{ .Values.apps.registryPublic.authPort }}
      targetPort: {{ .Values.apps.registryPublic.authPort }}
  selector:
    app: {{ .Values.apps.registryPublic.authAppName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.registryPublicUi.appName }}
  namespace: {{ .Values.apps.registryPublic.namespace }}
  labels:
    app: {{ .Values.apps.registryPublicUi.appName }}
spec:
  ports:
    - name: http
      port: {{ .Values.apps.registryPublicUi.port }}
      targetPort: {{ .Values.apps.registryPublicUi.port }}
  selector:
    app: {{ .Values.apps.registryPublicUi.appName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.registryPublicUiApi.appName }}
  namespace: {{ .Values.apps.registryPublic.namespace }}
  labels:
    app: {{ .Values.apps.registryPublicUiApi.appName }}
spec:
  ports:
    - name: http
      port: {{ .Values.apps.registryPublicUiApi.port }}
      targetPort: {{ .Values.apps.registryPublicUiApi.port }}
  selector:
    app: {{ .Values.apps.registryPublicUiApi.appName }}
