apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apps.registryPublic.secrets.ui }}
  namespace: {{ .Values.apps.registryPublic.namespace }}
  labels:
    app: {{ .Values.apps.registryPublicUi.appName }}
type: Opaque
stringData:
  SESSION_SECRET: __REGISTRY_PUBLIC_UI_SESSION_SECRET__
