apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.apps.demo.claims.config }}
  namespace: {{ .Values.apps.demo.namespace }}
  labels:
    app: {{ .Values.apps.demo.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apps.demo.storage }}
