apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apps.honcho.postgres.initScripts }}
  namespace: {{ .Values.apps.honcho.namespace }}
  labels:
    app: {{ .Values.apps.honcho.postgres.serviceName }}
data:
  01-vector.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
