networks:
  easyshell:
    external: true
  caddy-public:
    external: true
services:
  submission-manager:
    image: cr.guneet.xyz/easyshell/submission-manager:latest
    pull_policy: always
    container_name: easyshell-prod-submission-manager
    volumes:
      - /tmp/easyshell:/tmp/easyshell
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json:ro
    networks:
      - easyshell
    environment:
      APP: submission-manager
      DRIZZLE_PROXY_URL: http://db-proxy:8008
      DRIZZLE_PROXY_TOKEN: token
      DOCKER_REGISTRY: cr.guneet.xyz
    depends_on:
      db-proxy:
        condition: service_healthy
  session-manager:
    image: cr.guneet.xyz/easyshell/session-manager:latest
    pull_policy: always
    container_name: easyshell-prod-session-manager
    environment:
      TOKEN: token
      DOCKER_REGISTRY: cr.guneet.xyz
    networks:
      - easyshell
    volumes:
      - /tmp/easyshell:/tmp/easyshell
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json:ro
  db:
    container_name: easyshell-prod-db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    networks:
      - easyshell
  db-proxy:
    image: cr.guneet.xyz/easyshell/db-proxy:latest
    pull_policy: always
    container_name: easyshell-prod-db-proxy
    environment:
      DATABASE_URL: postgres://postgres:password@db/easyshell
      TOKEN: token
    networks:
      - easyshell
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 5s
      timeout: 1s
      retries: 3
    depends_on:
      db:
        condition: service_started
  website:
    image: cr.guneet.xyz/easyshell/website:latest
    pull_policy: always
    container_name: easyshell-prod-website
    environment:
      APP: website
      AUTH_TRUST_HOST: true
      DRIZZLE_PROXY_URL: http://db-proxy:8008
      DRIZZLE_PROXY_TOKEN: token
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: https://easyshell.sh
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SESSION_MANAGER_URL: http://session-manager:4000
      SESSION_MANAGER_TOKEN: token
      RESEND_API_KEY: ${RESEND_API_KEY}
      NEXT_PUBLIC_POSTHOG_KEY: ${NEXT_PUBLIC_POSTHOG_KEY}
    networks:
      - caddy-public
      - easyshell
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 1s
      retries: 3
    depends_on:
      db-proxy:
        condition: service_healthy
      session-manager:
        condition: service_started
      submission-manager:
        condition: service_started
