apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.ntfy.appName }}
  namespace: {{ .Values.apps.ntfy.namespace }}
  labels:
    app: {{ .Values.apps.ntfy.appName }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.apps.ntfy.port }}
      targetPort: {{ .Values.apps.ntfy.port }}
  selector:
    app: {{ .Values.apps.ntfy.appName }}
