apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.apps.openwebui.claims.data }}
  namespace: {{ .Values.apps.openwebui.namespace }}
  labels:
    app: {{ .Values.apps.openwebui.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apps.openwebui.storage.data }}
