apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.apps.zennotes.claims.workspace }}
  namespace: {{ .Values.apps.zennotes.namespace }}
  labels:
    app: {{ .Values.apps.zennotes.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apps.zennotes.storage.workspace }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.apps.zennotes.claims.data }}
  namespace: {{ .Values.apps.zennotes.namespace }}
  labels:
    app: {{ .Values.apps.zennotes.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apps.zennotes.storage.data }}
