services:
  ssh:
    build: .
    container_name: proxy
    volumes:
      - ./ssh_host_keys:/etc/ssh/keys
      - ./ssh_config:/root/.ssh:ro
    restart: always
    network_mode: service:tailscale
  tailscale:
    image: tailscale/tailscale:latest
    pull_policy: always
    hostname: proxy
    container_name: proxy-ts
    restart: always
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_AUTHKEY: ${TS_AUTHKEY}
    volumes:
      - ./tailscale:/var/lib/tailscale
    networks:
      - caddy-public
networks:
  caddy-public:
    external: true
