services:
  open-webui:
    pull_policy: always
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    networks:
      - caddy-private
    volumes:
      - ./data:/app/backend/data
  lite-llm:
    image: ghcr.io/berriai/litellm:main-latest
    pull_policy: always
    container_name: lite-llm
    restart: always
    volumes:
      - ./litellm:/config
      - ./litellm-data:/root/.config/litellm
    command: --config /config/config.yml
    environment:
      GITHUB_API_KEY: ${GITHUB_API_KEY}
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      DATABASE_URL: postgresql://postgres:password@lite-llm-db:5432/litellm
    networks:
      - caddy-private
    depends_on:
      lite-llm-db:
        condition: service_started
  lite-llm-db:
    container_name: lite-llm-db
    image: postgres:17
    pull_policy: always
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - caddy-private
    volumes:
      - ./litellm-db:/var/lib/postgresql/data
networks:
  caddy-private:
    external: true
