apiVersion: v1
kind: Secret
metadata:
  name: coturn-secret
  namespace: {{ .Values.apps.coturn.namespace }}
  labels:
    app: {{ .Values.apps.coturn.appName }}
type: Opaque
stringData:
  TURN_SHARED_SECRET: __TURN_SHARED_SECRET__
