apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.homepage.appName }}
  namespace: {{ .Values.apps.homepage.namespace }}
  labels:
    app: {{ .Values.apps.homepage.appName }}
spec:
  replicas: {{ .Values.apps.homepage.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apps.homepage.appName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.apps.homepage.appName }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      nodeSelector:
        role: primary
      serviceAccountName: {{ .Values.apps.homepage.appName }}
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      initContainers:
        - name: copy-config
          image: busybox:latest
          command:
            - sh
            - -c
            - cp /config-source/* /app/config/
          volumeMounts:
            - mountPath: /config-source
              name: config-source
              readOnly: true
            - mountPath: /app/config
              name: config
      containers:
        - name: homepage
          image: {{ .Values.apps.homepage.images.homepage.image }}:{{ .Values.apps.homepage.images.homepage.imageTag }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              memory: 256Mi
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "$(MY_POD_IP):3000,home.guneet.xyz"
          ports:
            - name: http
              containerPort: {{ .Values.apps.homepage.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: /app/config
              name: config
      volumes:
        - name: config-source
          configMap:
            name: {{ .Values.apps.homepage.configMaps.config }}
        - name: config
          emptyDir: {}
