apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apps.element.configMaps.config }}
  namespace: {{ .Values.apps.element.namespace }}
  labels:
    app: {{ .Values.apps.element.appName }}
data:
  config.json: |
    {
      "default_server_config": {
        "m.homeserver": {
          "base_url": "https://{{ .Values.apps.synapse.domain }}",
          "server_name": "{{ .Values.apps.synapse.domain }}"
        }
      },
      "brand": "Element",
      "disable_custom_urls": false,
      "disable_guests": true,
      "default_country_code": "US",
      "show_labs_settings": false,
      "features": {},
      "default_federate": true,
      "default_theme": "dark"
    }
