apiVersion: v1
kind: Secret
metadata:
  name: synapse-signing-key
  namespace: {{ .Values.apps.synapse.namespace }}
  labels:
    app: {{ .Values.apps.synapse.appName }}
type: Opaque
stringData:
  signing.key: |
    __SYNAPSE_SIGNING_KEY__
