apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.apps.synapse.namespace }}
  labels:
    app: {{ .Values.apps.synapse.appName }}
type: Opaque
stringData:
  SYNAPSE_DB_PASSWORD: __SYNAPSE_POSTGRES_PASSWORD__
  SYNAPSE_REGISTRATION_SHARED_SECRET: __SYNAPSE_REGISTRATION_SHARED_SECRET__
  SYNAPSE_MACAROON_SECRET_KEY: __SYNAPSE_MACAROON_SECRET_KEY__
  SYNAPSE_FORM_SECRET: __SYNAPSE_FORM_SECRET__
