apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: {{ .Values.apps.registry.namespace }}
  labels:
    app: {{ .Values.apps.registry.appName }}
type: Opaque
stringData:
  htpasswd: __REGISTRY_HTPASSWD__
