apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.apps.caddyPublic.claims.caddy }}
  namespace: {{ .Values.apps.caddyPublic.namespace }}
  labels:
    app: {{ .Values.apps.caddyPublic.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
