apiVersion: v1
data:
  Caddyfile: |
    {
    	email guneetaggarwal@gmail.com
    	acme_dns cloudflare {env.CLOUDFLARE_API_TOKEN}
    }
    
    walls.guneet.dev {
    	reverse_proxy {{ .Values.apps.walls.serviceName }}:{{ .Values.apps.walls.port }}
    }

kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.apps.caddyPublic.appName }}
  name: {{ .Values.apps.caddyPublic.configMaps.caddyfile }}
  namespace: {{ .Values.apps.caddyPublic.namespace }}
