apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secret
  namespace: {{ .Values.apps.caddyPublic.namespace }}
  labels:
    app: {{ .Values.apps.caddyPublic.appName }}
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: __CLOUDFLARE_API_TOKEN__
