apiVersion: v1
kind: Secret
metadata:
  name: coordinator-secret
  namespace: {{ .Values.apps.easyshellCoordinator.namespace }}
  labels:
    app: {{ .Values.apps.easyshellCoordinator.appName }}
type: Opaque
stringData:
  DATABASE_URL: postgresql://{{ .Values.apps.easyshell.postgres.dbUser }}:{{ .Values.apps.easyshell.postgres.dbPassword }}@{{ .Values.apps.easyshell.postgres.serviceName }}:{{ .Values.apps.easyshell.postgres.port }}/{{ .Values.apps.easyshell.postgres.dbName }}
  COORDINATOR_TOKEN: __EASYSHELL_COORDINATOR_TOKEN__
  COORDINATOR_REGISTRATION_TOKEN: __EASYSHELL_COORDINATOR_REGISTRATION_TOKEN__
  COORDINATOR_SECRET_KEY: __EASYSHELL_COORDINATOR_SECRET_KEY__
  COORDINATOR_PORT: "{{ .Values.apps.easyshellCoordinator.port }}"
  MAX_ATTEMPTS: "3"
  LOG_LEVEL: "info"
  NODE_ENV: "production"
