apiVersion: v1
kind: Secret
metadata:
  name: registry-pull-secret
  namespace: {{ .Values.apps.easyshell.namespace }}
  labels:
    app: {{ .Values.apps.easyshell.appName }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: __EASYSHELL_REGISTRY_DOCKERCONFIG_JSON__
