apiVersion: v1
kind: Secret
metadata:
  name: website-secret
  namespace: {{ .Values.apps.easyshell.namespace }}
  labels:
    app: {{ .Values.apps.easyshell.appName }}
type: Opaque
stringData:
  NEXTAUTH_URL: "https://{{ .Values.apps.easyshell.domain }}"
  NEXTAUTH_SECRET: __EASYSHELL_NEXTAUTH_SECRET__
  AUTH_TRUST_HOST: "true"
  DATABASE_URL: postgresql://{{ .Values.apps.easyshell.postgres.dbUser }}:{{ .Values.apps.easyshell.postgres.dbPassword }}@{{ .Values.apps.easyshell.postgres.serviceName }}:{{ .Values.apps.easyshell.postgres.port }}/{{ .Values.apps.easyshell.postgres.dbName }}
  COORDINATOR_URL: http://{{ .Values.apps.easyshellCoordinator.appName }}.{{ .Values.apps.easyshellCoordinator.namespace }}.svc.cluster.local:{{ .Values.apps.easyshellCoordinator.port }}
  COORDINATOR_TOKEN: __EASYSHELL_COORDINATOR_TOKEN__
  DISCORD_CLIENT_ID: __EASYSHELL_DISCORD_CLIENT_ID__
  DISCORD_CLIENT_SECRET: __EASYSHELL_DISCORD_CLIENT_SECRET__
  GITHUB_CLIENT_ID: __EASYSHELL_GITHUB_CLIENT_ID__
  GITHUB_CLIENT_SECRET: __EASYSHELL_GITHUB_CLIENT_SECRET__
  GOOGLE_CLIENT_ID: __EASYSHELL_GOOGLE_CLIENT_ID__
  GOOGLE_CLIENT_SECRET: __EASYSHELL_GOOGLE_CLIENT_SECRET__
  SMTP_HOST: {{ .Values.smtp.host }}
  SMTP_PORT: "{{ .Values.smtp.port }}"
  SMTP_USERNAME: __SMTP_USERNAME__
  SMTP_PASSWORD: __SMTP_PASSWORD__
  SMTP_MAIL_FROM: {{ .Values.smtp.mailFrom }}
  POSTHOG_HOST: __EASYSHELL_POSTHOG_HOST__
  NEXT_PUBLIC_POSTHOG_KEY: __EASYSHELL_POSTHOG_KEY__
