name: dev-db
services:
  postgres:
    container_name: dev-db
    hostname: dev-db
    image: postgres:17
    ports:
      - 100.100.2.1:5432:5432
    pull_policy: always
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - default
      - dev-db
  pgui:
    container_name: dev-db-ui
    image: kvqn/pgui:latest
    pull_policy: always
    restart: always
    env_file: .env
    networks:
      - default
      - caddy-private
  proxy:
    container_name: dev-db-proxy
    image: kvqn/db-proxy:latest
    pull_policy: always
    restart: always
    networks:
      - default
      - caddy-private
      - dev-db
    environment:
      TOKEN: token
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
networks:
  default:
  caddy-private:
    external: true
  dev-db:
    external: true
