apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.apps.infisical.namespace }}
  labels:
    app: {{ .Values.apps.infisical.appName }}
type: Opaque
stringData:
  ENCRYPTION_KEY: __INFISICAL_ENCRYPTION_KEY__
  AUTH_SECRET: __INFISICAL_AUTH_SECRET__
  DB_CONNECTION_URI: __INFISICAL_DB_CONNECTION_URI__
  REDIS_URL: redis://{{ .Values.apps.infisical.redis.serviceName }}:{{ .Values.apps.infisical.redis.port }}
  SITE_URL: "https://{{ .Values.apps.infisical.domain }}"
  SMTP_HOST: {{ .Values.smtp.host }}
  SMTP_PORT: "{{ .Values.smtp.port }}"
  SMTP_USERNAME: __SMTP_USERNAME__
  SMTP_PASSWORD: __SMTP_PASSWORD__
  SMTP_FROM_ADDRESS: {{ .Values.smtp.mailFrom }}
  SMTP_FROM_NAME: {{ .Values.apps.infisical.smtpFromName }}
