apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-config
  namespace: {{ .Values.apps.coturn.namespace }}
  labels:
    app: {{ .Values.apps.coturn.appName }}
data:
  turnserver.conf: |
    listening-port=3478
    tls-listening-port=5349
    min-port={{ .Values.apps.coturn.relayPortMin }}
    max-port={{ .Values.apps.coturn.relayPortMax }}
    realm=${REALM}
    external-ip=${EXTERNAL_IP}
    use-auth-secret
    static-auth-secret=${TURN_SHARED_SECRET}
    cert=/certs/turn.matrix.guneet.dev.crt
    pkey=/certs/turn.matrix.guneet.dev.key
    cipher-list=ECDHE+AESGCM:ECDHE+CHACHA20:DHE+AESGCM:!aNULL:!MD5
     no-tlsv1
     no-tlsv1_1
     denied-peer-ip=10.0.0.0-10.255.255.255
     denied-peer-ip=192.168.0.0-192.168.255.255
     denied-peer-ip=172.16.0.0-172.31.255.255
     denied-peer-ip=127.0.0.0-127.255.255.255
     denied-peer-ip=::1
     denied-peer-ip=224.0.0.0-239.255.255.255
    no-cli
    pidfile=/var/run/turnserver.pid
    log-file=stdout
    simple-log
