{{- range $variant := list "public" "private" }}
{{- $variantValues := index $.Values.apps.caddy $variant }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.apps.caddy.appName }}-{{ $variant }}
  namespace: {{ $.Values.apps.caddy.namespace }}
  labels:
    app: {{ $.Values.apps.caddy.appName }}-{{ $variant }}
spec:
  replicas: {{ $variantValues.replicas }}
  selector:
    matchLabels:
      app: {{ $.Values.apps.caddy.appName }}-{{ $variant }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ $.Values.apps.caddy.appName }}-{{ $variant }}
      annotations:
        checksum/caddyfile: {{ include (print $.Template.BasePath "/" $variant "-configmap.yaml") $ | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/cloudflare-secret.yaml") $ | sha256sum }}
    spec:
      nodeSelector:
        role: primary
      containers:
        - name: caddy
          image: {{ $.Values.apps.caddy.images.caddy.image }}:{{ $.Values.apps.caddy.images.caddy.imageTag }}
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 256Mi
          env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: CLOUDFLARE_API_TOKEN
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 443
              protocol: UDP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: caddyfile
              subPath: Caddyfile
            - mountPath: /data
              name: {{ $.Values.apps.caddy.claims.data }}
      volumes:
        - name: caddyfile
          configMap:
            name: {{ $variantValues.configMaps.caddyfile }}
            items:
              - key: Caddyfile
                path: Caddyfile
        - name: {{ $.Values.apps.caddy.claims.data }}
          persistentVolumeClaim:
            claimName: {{ $.Values.apps.caddy.claims.data }}
{{- end }}
