apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apps.caddy.private.configMaps.caddyfile }}
  namespace: {{ .Values.apps.caddy.namespace }}
  labels:
    app: {{ .Values.apps.caddy.appName }}
data:
  Caddyfile: |
    {
    	email guneetaggarwal@gmail.com
    	acme_dns cloudflare {env.CLOUDFLARE_API_TOKEN}
    }
    
    :80 {
    	respond /healthz 200
    }
    
    headlamp.guneet.xyz {
    	reverse_proxy {{ .Values.apps.headlamp.appName }}.{{ .Values.apps.headlamp.namespace }}.svc.cluster.local:{{ .Values.apps.headlamp.port }}
    }
    
    llm.guneet.xyz {
    	reverse_proxy {{ .Values.apps.litellm.appName }}.{{ .Values.apps.litellm.namespace }}.svc.cluster.local:{{ .Values.apps.litellm.port }}
    }

    chat.guneet.xyz {
    	reverse_proxy {{ .Values.apps.openwebui.appName }}.{{ .Values.apps.openwebui.namespace }}.svc.cluster.local:{{ .Values.apps.openwebui.port }}
    }

    cr.guneet.xyz {
    	reverse_proxy /v2/* {{ .Values.apps.registry.appName }}.{{ .Values.apps.registry.namespace }}.svc.cluster.local:{{ .Values.apps.registry.port }}
    	reverse_proxy {{ .Values.apps.registryUi.appName }}.{{ .Values.apps.registryUi.namespace }}.svc.cluster.local:{{ .Values.apps.registryUi.port }}
    }

    portainer.guneet.xyz {
    	reverse_proxy {{ .Values.apps.portainer.appName }}.{{ .Values.apps.portainer.namespace }}.svc.cluster.local:{{ .Values.apps.portainer.port }}
    }
