apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.apps.caddy.claims.data }}
  namespace: {{ .Values.apps.caddy.namespace }}
  labels:
    app: {{ .Values.apps.caddy.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apps.caddy.storage }}
