apiVersion: v1
kind: Secret
metadata:
  name: ssh-secret
  namespace: {{ .Values.apps.demo.namespace }}
  labels:
    app: {{ .Values.apps.demo.appName }}
type: Opaque
stringData:
  authorized_keys: __DEMO_SSH_AUTHORIZED_KEYS__
